### ISSUE TITLE
Self Signed TLS Certificates

### ISSUE THREAD

**Issue by 256dpi** [256dpi/processing-mqtt#10]

**Comment by 256dpi** [comment]
Done

**Comment by markusand** [comment]
Nice piece of software, I like its simplicity. I’ve been having a look and couldn’t find a way to define a self signed certificate to connect via TLS. Is there any way to do it, or any plan to implement it? Thanks in advance

**Comment by 256dpi** [comment]
Thanks. That's not yet supported. I'm happy to receive PRs on that as I'm quite busy ATM.

**Comment by 256dpi** [comment]
Closing as outdated. Please reopen if problem persists.
