### ISSUE TITLE
Graphics code called within an MQTTCallback crashed Processing

### ISSUE THREAD

**Issue by marqrdt** [256dpi/processing-mqtt#11]
Hi,
   I'm getting JVM crashes in Processing 3.1.1 anytime I make any sort of Graphics call inside a messageArrived() method in my MQTTCallback implementation. If I make the same graphics calls outside messageArrived(), they never crash. You can read more on my original post in the Processing project: https://github.com/processing/processing/issues/4585

Thanks,
Paul

**Comment by 256dpi** [comment]
Hi Paul, Thanks for report this, I'll look into it as fast as I can. What version of the processing-mqtt library are you using?

**Comment by 256dpi** [comment]
In the mean time I tested the following sketch with the most recent version of processing-mqtt without any errors:

``` java
import mqtt.*;

MQTTClient client;

void setup() {
  size(400, 400);

  client = new MQTTClient(this);
  client.connect("mqtt://try:try@broker.shiftr.io", "processing");
  client.subscribe("/example");
}

void draw() {
  background(255);
}

void keyPressed() {
  client.publish("/example", "");
}

void messageReceived(String topic, byte[] payload) {
  background(0);
}
```

Could you test the sketch and report if processing crashes here as well?

**Comment by marqrdt** [comment]
Hi Joël,
   You can go ahead and close this. It turns out I was using the Paho MqttClient class itself rather than your wrapper. I looked at the code in your plugin and was able to get it working. Sorry for the bother. This is a fantastic plugin that I plan on using for a sort of "render farm" of Processing nodes.

Regards,
Paul
