### ISSUE TITLE
Username and password.

### ISSUE THREAD

**Issue by miokato** [256dpi/processing-mqtt#12]
Hi.
I'm using this library with Cloud Mqtt service.(https://www.cloudmqtt.com)
This service demand username and password.
Please add a function to set there.

Regards,
MIO.

**Comment by 256dpi** [comment]
Hi @miokato.

You can specify a username and password via the URL:

``` java
client.connect("mqtt://USERNAME:PASSWORD@broker.example.com", "processing");
```
