### ISSUE TITLE
ID e Passsword

### ISSUE THREAD

**Issue by ghost** [256dpi/processing-mqtt#13]
I want to connect Processing with The Things Network MQTT broker.

https://www.thethingsnetwork.org/docs/applications/mqtt/quick-start.html

But I don't know where insert Password and AppID that TTN provides me.
Is it possible?

**Comment by 256dpi** [comment]
This library extracts all connections details from a connection [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax).

In that sense, you need to add the id and password tho the first string argument of `connect`:

```java
client.connect("mqtt://APP_ID:PASSWORD@HOST", "processing");
```

**Comment by 256dpi** [comment]
I guest that problem has been solved.
