### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by erwrow** [256dpi/processing-mqtt#14]
Hi, ¿how can i know when i've lost the connection?

**Comment by 256dpi** [comment]
Unfortunately, this is not supported at the moment and I don't have much time to implement it.... Sorry.

**Comment by 256dpi** [comment]
Duplicate of #6.

**Comment by erwrow** [comment]
Sorry for insisting, but it's not a duplicate. When i loss connection, or i can't connect your librarie throws an exception over the console with something like this: [MQTT] failed to subscribe:... and then say that the client isn't connected, i want to pass that output to the screen so the user knows what's happening

**Comment by 256dpi** [comment]
I see, I'll think about a fix for that.

**Comment by cimba007** [comment]
Any progress on this issue?

**Comment by 256dpi** [comment]
Done in `v1.7.0`.
