### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by efrenbg1** [256dpi/processing-mqtt#17]
Hi, I found very useful this library as it works perfectly. But I find an issue with it.
I did not find any way of getting the status of the connection. Also when connecting (with not internet), the library passes the error as a message which seems imposible to catch with any function. The thing is if there is any function that returns the status of the connection?

Thanks

**Comment by 256dpi** [comment]
Done in `v1.7.0` (callbacks can be used to track the connection status).
