### ISSUE TITLE
Example not working with version 1.6.3

### ISSUE THREAD

**Issue by pasine** [256dpi/processing-mqtt#20]
The example is not working with the latest version available on library manager (1.6.3).  
I would recommend to either update the version on library manager or to put a reference to the issue.

**Comment by 256dpi** [comment]
What was the error? In any case, I released a new version which you can check out.

**Comment by pasine** [comment]
No error. The example simply doesn't do anything. I thought it might be the automatic callback was not available on version 1.6.3.

**Comment by 256dpi** [comment]
Closing as outdated. Please reopen if problem persists.
