### ISSUE TITLE
When client is not connected, PApplet.dispose() always crashing

### ISSUE THREAD

**Issue by elRadish** [256dpi/processing-mqtt#23]
When the connection of the client failed before, closing the application fails because the client can't disconnect and throws and exception.
My workaround:

`void dispose(){
  try{
    super.dispose();
  } catch (Throwable t){ }
}
`

**Comment by coriolan-v** [comment]
Hi @elRadish, I have the same problem, how do you use this workaround? Thanks

**Comment by 256dpi** [comment]
The latest release will catch the error and discard it.
