### ISSUE TITLE
topic use of *

### ISSUE THREAD

**Issue by kllsamui** [256dpi/processing-mqtt#25]
play from processing 3.5.3. / raspberry pi /

i wanted to try
```
String mqtt_out    = "pcu/sensor/out";
String mqtt_in      = "pcu/in";
String mqtt_sub    = "/";    // also try  /*   or  *  or pcu/*   // test subscribe some topic

client.subscribe(mqtt_sub);
```
but not catch any of it unless i use the exact topic like in mqtt_out or mqtt_in
did i miss something?

**Comment by 256dpi** [comment]
"*" is not a valid wildcard, you need to use "+".

**Comment by kllsamui** [comment]
thanks, works partially, but not for both
i try
```
"pcu/+" and "pcu/+/+"
```
and can only catch one

also try 
>List of string and integer tuples
e.g. subscribe([("my/topic", 0), ("another/topic", 2)])

```
String[] mqtt_sub    = {"pcu213/+/+","pcu213/+"}; 
```

but not work from processing

**Comment by OliverESP** [comment]
Hello 256dpi,
have you a solution about my Problem?
Can you decribe an multi subscribe example  e.g.

Temperatur
Humidity
Pressure

client.subscribe(T_topic);
client.subscribe(P_topic); 
 client.subscribe(H_topic);

Thanks in Advance OlliP

**Comment by 256dpi** [comment]
The "+" wildcard will match one segment. As an alternative you can use "#" to match any segments.
