### ISSUE TITLE
How to connect to a broker that requires a username and password?

### ISSUE THREAD

**Issue by ohbhatt** [256dpi/processing-mqtt#27]
I use CloudMQTT as my broker. It requires me to connect to it using a username and password.
client.connect only has the following options: 
- public void connect(String brokerURI)
- public void connect(String brokerURI, String clientID)
- public void connect(String brokerURI, String clientId, boolean cleanSession)

I don't know how to connect to my broker as it doesn't give me a URI. It gives me the following details:
- Host (a url)
- Username
- Password
- Port

I can't figure out if I can use MqttConnectOptions or MqttConnectOptions.userame to set my client.connect options.

Please help.

**Comment by 256dpi** [comment]
You need to combine the parts to an URI e.g. "mqtt://user:pass@host:port".

**Comment by ohbhatt** [comment]
Thanks! It worked.
It would be really great if the library had a method for the same. As a newbie I got confused.
I really appreciate your work.
