### ISSUE TITLE
How to instantiate multiple clients connecting to different brokers from one .pde

### ISSUE THREAD

**Issue by dattasaurabh82** [256dpi/processing-mqtt#29]
_It's not really an error but more of a request to show an example for a not so special use case:_  

**Scenario:**
I have a sketch and it should connect to 2 different MQTT brokers. 

To instantiate one instance:
```
MQTTClient localClient;
localClient = new MQTTClient(this);
```
And then the global events from the interface are, as described in your  [MQTTListener.java](https://github.com/256dpi/processing-mqtt/blob/master/src/mqtt/MQTTListener.java) are:
```
void clientConnected();
void connectionLost();
void messageReceived(String topic, byte[] payload);
```

Now to instantiate a new client in the same sketch, first I can instantiate another something like this:
```
MQTTClient remoteClient;
```

Now the question is, what should be here?
`remoteClient = new MQTTClient(this, <Listener??>);`
And where to define that with my custom event functions and how ?
An example would be awesome, as I don't know much of Java.

**Comment by 256dpi** [comment]
You can provided a class that implements `MQTTListener` to dispatch the events to custom objects rather than the global functions. This way you can differentiate the events from multiple clients. I'm sorry, but I don't have the time ATM to build a full example.

**Comment by dattasaurabh82** [comment]
> You can provided a class that implements `MQTTListener` to dispatch the events to custom objects rather than the global functions. This way you can differentiate the events from multiple clients. I'm sorry, but I don't have the time ATM to build a full example.

Hey @256dpi I appreciate your effort to quickly post a reply.
I'm guessing you misunderstood my request about _example_ . 

Just to clarify, I'm asking if you can help by posting a code snippet here about a `MQTTclient` instantiation that goes into a little bit more in depth on how to include custom event handlers with your above mentioned custom class code snippet rather than just : 

> Alternatively you can provide your own Listener class instead of relying on global methods:
> `MQTTClient client = new MQTTClient(PApplet parent, Listener listener);`
> You can find the interface here: [MQTTListener.java](https://github.com/256dpi/processing-mqtt/blob/master/src/mqtt/MQTTListener.java). 

That would be very helpful for us joe's. 

But if you don't have time at all, I understand.

**Comment by 256dpi** [comment]
Ah I see. You can instantiate multiple clients in the following way:

```java
// MyHandler must implement MQTTListener
MyHandler handler1 = new MyHandler();
MyHandler handler2 = new MyHandler();

MQTTClient client1 = new MQTTClient(this, handler1);
MQTTClient client2 = new MQTTClient(this, handler2);
```

**Comment by dattasaurabh82** [comment]
> Ah I see. You can instantiate multiple clients in the following way:
> 
> ```java
> // MyHandler must implement MQTTListener
> MyHandler handler1 = new MyHandler();
> MyHandler handler2 = new MyHandler();
> 
> MQTTClient client1 = new MQTTClient(this, handler1);
> MQTTClient client2 = new MQTTClient(this, handler2);
> ```

Thanks 
and for example  a sup[er simple `MyHandler` would look something like as below: ??
( It took me a while to learn and understand `implements`. I didn't know)
Explanation of `implements` are [here](https://docs.oracle.com/javase/tutorial/java/IandI/usinginterface.html) and [here](https://www.geeksforgeeks.org/interfaces-in-java/)

```java
class MyHandler implements MQTTListener {
    // constructor
    MyHandler(){
    }
   
    // methods from MQTTListener
    void clientConnected() {
        //
    }
    void connectionLost() {
        // 
    }
    void messageReceived(String topic, byte[] payload) {
        //
    }
}
```
