### ISSUE TITLE
request

### ISSUE THREAD

**Issue by ravibutani** [256dpi/processing-mqtt#5]
Hii dear, your Library works out of box with processing...
which QoS level you have implemented currently?
if it is more than 0 than how to change it in code...?
as once net is disconnected and even sending mqtt publish... I am getting it on other PC when the net connects again so i think its not QoS0...

**Comment by 256dpi** [comment]
Hi @ravibutani, the library uses QoS0 for subscribing and publishing. The underlying library supports up to QoS2 but that functionality hasn't been exposed yet. Pull-requests are welcome! ;)

But your problem sounds more like the messages get retained by the broker and published to connecting clients upon subscription. What kind of broker are you using?

**Comment by ravibutani** [comment]
I am using iot.eclipse.org client... 
Thanks for contributions of mqtt lib..

Ravi

---

**Comment by 256dpi** [comment]
Actually the functionality is already exposed as you can see here:

``` java
  /**
   * Publish a message with a topic, payload qos and retain flag.
   *
   * @param topic
   * @param payload
   * @param qos
   * @param retained
   */
  public void publish(String topic, byte[] payload, int qos, boolean retained) {
    try {
      client.publish(topic, payload, qos, retained);
    } catch (MqttException e) {
      System.out.println("[MQTT] failed to publish: " + e.getMessage());
    }
  }
```
