### ISSUE TITLE
Receive all incoming messages

### ISSUE THREAD

**Issue by sulram** [256dpi/processing-mqtt#9]
Hello there! Thanks for this nice library

Is there a way to receive all incoming messages, like OSC behavior, or we need to know exactly the name of channels to subscribe?

Thanks in advance,

Marlus

**Comment by 256dpi** [comment]
With MQTT you can make a firehose subscription to get all messages published to the broker:

``` java
client.subscribe("#");
```

Does that help?

**Comment by sulram** [comment]
Yes! That's it, thank you!
